[project]
name = "core"
version = "0.1.0"
description = "Add a short description here"
authors = ["Miles Smith <miles-smith@omrf.org>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.11.9"
pip = ">=24.2,<25"
h5py = ">=3.11.0,<4"
hdf5 = ">=1.14.3,<2"
louvain = ">=0.8.2,<0.9"
leidenalg = ">=0.10.2,<0.11"
numpy = ">=1.26.4,<2"
pandas = ">=2.2.2,<3"
pandoc = ">=3.3,<4"
anndata = ">=0.10.8,<0.11"
scanpy = ">=1.10.2,<2"
muon = ">=0.1.6,<0.2"
mudata = ">=0.2.4,<0.3"
scipy = ">=1.14.0,<2"
scikit-learn = ">=1.5.1,<2"
