steps:
- name: 'gcr.io/cloud-builders/docker:latest'
  args: [ 'build',
          '--build-arg', 'PROJECT=$PROJECT_ID',
          '--build-arg', '_REPO=${_REPO}',
          '--build-arg', '_SHIPYARD=${_SHIPYARD}',
          '--build-arg', '_PARENT=${_PARENT}',
          '--build-arg', '_PARENT_VERSION=${_PARENT_VERSION}',
          '--build-arg', '_PARENT_VARIANT=${_PARENT_VARIANT}',
          '--build-arg', '_QUARTO_VERSION',
          '--build-arg', '_BIOCONDUCTOR_VERSION=${_BIOCONDUCTOR_VERSION}',
          '--build-arg', '_BIOCONDUCTOR_PATCH=${_BIOCONDUCTOR_PATCH}',

          '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/${_SHIPYARD}/bioconductor:${_BIOCONDUCTOR_VERSION}-${_BIOCONDUCTOR_PATCH}',
          '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/${_SHIPYARD}/bioconductor:latest',
          '.' ]
  env:
    - "DOCKER_BUILDKIT=1"
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/${_SHIPYARD}/bioconductor'
substitutions:
    _VERSION: 4.2.1
    _PARENT: rocker
    _PARENT_VARIANT: rstudio
    _PARENT_VERSION: 4.2.1
    _REPO: us-central1-docker.pkg.dev
    _SHIPYARD: utopia-planitia
    _BIOCONDUCTOR_VERSION: "3.16"
    _BIOCONDUCTOR_PATCH: "27"
    _QUARTO_VERSION: 1.1.251
options:
    substitution_option: 'ALLOW_LOOSE'