#cloud-config

users:
- name: jupyter
  uid: 2000

write_files:
- path: /etc/systemd/system/jupyterlab.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Jupyterlab container

    [Service]
    ExecStart=/usr/bin/docker run -it -u 2000 --name=jupyterlab -d -p 8888:8888 --volume /var/lib/nvidia/lib64:/usr/local/nvidia/lib64 \
      --volume /var/lib/nvidia/bin:/usr/local/nvidia/bin \
      --device /dev/nvidia0:/dev/nvidia0 \
      --device /dev/nvidia-uvm:/dev/nvidia-uvm \
      --device /dev/nvidiactl:/dev/nvidiactl \
      --ipc=host \
      --ulimit memlock=-1 \
      --ulimit stack=67108864 \
      nvcr.io/nvidia/pytorch:23.07-py3
    ExecStop=/usr/bin/docker stop jupyterlab
    ExecStopPost=/usr/bin/docker rm jupyterlab

runcmd:
- systemctl daemon-reload
- systemctl start jupyterlab.service

# Optional once-per-boot setup. For example: mounting a PD.
bootcmd:
- fsck.ext4 -tvy /dev/[DEVICE_ID]
- mkdir -p /mnt/disks/[MNT_DIR]
- mount -t ext4 -O ... /dev/[DEVICE_ID] /mnt/disks/[MNT_DIR]
