[tool.poetry]
name = "dummy"
version = "0.1.0"
description = ""
authors = ["Miles Smith <mileschristiansmith@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.13"
anndata = "^0.10.6"
black = "^24.3.0"
cython = "^3.0.9"
h5py = "^3.10.0"
ipython = "^8.22.2"
ipywidgets = "^8.1.2"
jax = "^0.4.25"
jupyter-black = "^0.3.4"
jupyter-collaboration = "^2.0.5"
jupyterlab = "^4.1.5"
jupyterlab-execute-time = "^3.1.2"
jupyterlab-pygments = "^0.3.0"
jupyterlab-widgets = "^3.0.10"
jupytext = "^1.16.1"
leidenalg = "^0.10.2"
levenshtein = "^0.25.0"
loguru = "^0.7.2"
loompy = "^3.0.7"
matplotlib = "^3.8.3"
more-itertools = "^10.2.0"
mudata = "^0.2.3"
numba = "^0.59.1"
numexpr = "^2.9.0"
numpy = "^1.26.4"
pip = "^24.0"
poetry = "^1.8.2"
polars = "^0.20.16"
python-igraph = "^0.11.4"
python-levenshtein = "^0.25.0"
torch = "^2.2.2"
pytorch-lightning = "^2.2.1"
rich = "^13.7.1"
rpy2 = "^3.5.15"
scanpy = "^1.10.0"
scikit-image = "^0.22.0"
scikit-learn = "^1.4.1.post1"
scikit-misc = "^0.3.1"
scipy = "^1.12.0"
scirpy = "^0.16.0"
scrublet = "^0.2.3"
scvelo = "^0.3.2"
scvi-tools = "^1.1.2"
snapatac2 = "^2.6.0"
statsmodels = "^0.14.1"
tqdm = "^4.66.2"
umap-learn = "^0.5.5"
widgetsnbextension = "^4.0.10"
xlrd = "^2.0.1"
fastparquet = "^2024.2.0"
kaleido = "0.2.1"
harmonypy = {git = "https://github.com/slowkow/harmonypy", rev = "182a5c6e0fc954cb0b4db5074e507adb7a8293f3"}
revseq = ">=1.0.0"
muon = {git = "https://github.com/milescsmith/muon.git", rev = "version_update"}
fingerling = {git = "https://github.com/milescsmith/fingerling", rev = "0.1.1"}
tensorflow = "^2.16.1"
tensorflow-probability = "^0.24.0"
vaeda = { git = "https://github.com/kostkalab/vaeda", rev = "36cdc53"}
setuptools = "^69.2.0"