[project]
name = "dummy"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "anndata>=0.10.7",
    "arrow>=1.3.0",
    "black>=24.4.2",
    "cython>=3.0.10",
    "h5py>=3.11.0",
    "ipython>=8.24.0",
    "ipywidgets>=8.1.2",
    "jax>=0.4.26",
    "jupyter-black>=0.3.4",
    "jupyter-collaboration>=2.1.0",
    "jupyterlab>=4.1.8",
    "jupyterlab-execute-time>=3.1.2",
    "jupyterlab-pygments>=0.3.0",
    "jupyterlab-widgets>=3.0.10",
    "jupytext>=1.16.1",
    "leidenalg>=0.10.2",
    "levenshtein>=0.25.1",
    "loguru>=0.7.2",
    "loompy>=3.0.7",
    "matplotlib>=3.8.4",
    "more-itertools>=10.2.0",
    "mudata>=0.2.3",
    "numba>=0.59.1",
    "numexpr>=2.10.0",
    "numpy>=1.26.4",
    "numpy-groupies>=0.11.1",
    "pandas>2.1.0, <2.1.2",
    "pcre2>=0.4.0",
    "pip>=24.0",
    "plotly>=5.22.0",
    "poetry>=1.8.2",
    "polars>=0.20.23",
    "python-igraph>=0.11.4",
    "python-levenshtein>=0.25.1",
    "pytorch>=1.0.2",
    "pytorch-lightning>=2.2.4",
    "rich>=13.7.1",
    "rpy2==3.5.2",
    "scanpy>=1.10.1",
    "scikit-image>=0.23.2",
    "scikit-learn>=1.4.2",
    "scikit-misc>=0.3.1",
    "scipy>=1.13.0",
    "scirpy>=0.16.1",
    "scrublet>=0.2.3",
    "scvelo>=0.3.2",
    "scvi-tools>=1.1.2",
    "seaborn>=0.13.2",
    "snapatac2>=2.6.0",
    "statsmodels>=0.14.2",
    "tqdm>=4.66.2",
    "umap-learn>=0.5.6",
    "widgetsnbextension>=4.0.10",
    "xarray>=2024.3.0",
    "xlrd>=2.0.1",
    "jupyterlab_execute_time>=3.1.2",
    "jupyterlab_pygments>=0.3.0",
    "jupyterlab_widgets>=3.0.10",
    "numpy_groupies>=0.11.1",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/dummy"]
